version: '3'

x-minio-common: &minio-common
  image: quay.io/minio/minio:RELEASE.2023-09-30T07-02-29Z
  command: server --console-address ":9001" http://minio{1...4}/data{1...2}
  expose:
    - "9000"
    - "9001"
  environment:
    MINIO_ROOT_USER: minioadmin
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  postgresql:
    image: docker.io/bitnami/postgresql:15
    environment: 
      - POSTGRESQL_USERNAME=net_keycloak
      - POSTGRESQL_PASSWORD=keycloak_password
      - POSTGRESQL_DATABASE=bitnami_keycloak
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/net/keycloak/postgresql

  hr_db:
    image: docker.io/bitnami/postgresql:15
    environment:
      - POSTGRESQL_USERNAME=net_admin
      - POSTGRESQL_PASSWORD=net_password
      - POSTGRESQL_DATABASE=net_hr
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/net/hr/postgresql

  inventory_db:
    image: docker.io/bitnami/postgresql:15
    environment:
      - POSTGRESQL_USERNAME=net_admin
      - POSTGRESQL_PASSWORD=net_password
      - POSTGRESQL_DATABASE=net_inventory
    ports:
      - "5434:5432"
    volumes:
      - postgresql_data:/net/inventory/postgresql

  keycloak:
    image: docker.io/bitnami/keycloak:23
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DATABASE_HOST=postgresql
      - KEYCLOAK_DATABASE_PORT_NUMBER=5432
      - KEYCLOAK_DATABASE_NAME=bitnami_keycloak
      - KEYCLOAK_DATABASE_USER=net_keycloak
      - KEYCLOAK_DATABASE_PASSWORD=keycloak_password
      - KEYCLOAK_DATABASE_EXTERNAL=true
      - KEYCLOAK_LOGLEVEL=DEBUG
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_HTTPS_PORT=8081
    depends_on:
      - postgresql
    expose:
      - "8080"
      - "8081"

  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - data1-1:/data1
      - data1-2:/data2

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - data2-1:/data1
      - data2-2:/data2

  minio3:
    <<: *minio-common
    hostname: minio3
    volumes:
      - data3-1:/data1
      - data3-2:/data2

  minio4:
    <<: *minio-common
    hostname: minio4
    volumes:
      - data4-1:/data1
      - data4-2:/data2

  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
      - "9001:9001"
      - "8080:8080"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - keycloak

volumes:
  data1-1:
  data1-2:
  data2-1:
  data2-2:
  data3-1:
  data3-2:
  data4-1:
  data4-2:
  postgresql_data:
    driver: local 
